name: mydemoapp
services:
  # mariadb:
  #   image: mariadb:latest
  #   restart: always
  #   environment:
  #     MARIADB_DATABASE: order
  #     MARIADB_ROOT_PASSWORD: 1234
  #     MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - mariadb
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpw
      MONGO_INITDB_DATABASE: order
    volumes: 
      - mongodb-data:/data/db
    ports: 
      - 27017:27017
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  # mysql-data:
  redis-data:
  mongodb-data:
  