mutation ($orderId: String!, $orderItems: [OrderItemInput]!, $version: Int!) {
  updateOrder(orderId: $orderId, orderItems: $orderItems, version: $version) {
    id
    orderItems {
      menuId
      count
    }
  }
}
